//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Ordem_Serviço = new HashSet<Ordem_Serviço>();
        }
    
        public int Id { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Raca { get; set; }
        public int Id_Especie { get; set; }
        public int Id_Funcionario { get; set; }
        public string Nome { get; set; }
        public System.DateTime Idade { get; set; }
        public string Observacao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Raca Raca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordem_Serviço> Ordem_Serviço { get; set; }
    }
}
