//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordem_Serviço
    {
        public int Id { get; set; }
        public int Id_Animal { get; set; }
        public int Id_Funcionario { get; set; }
        public System.DateTime DT_Entrada { get; set; }
        public Nullable<System.DateTime> DT_Saida { get; set; }
        public string Hora_Entrada { get; set; }
        public string Hora_Saida { get; set; }
        public int Id_Servico { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Nome_Deixou { get; set; }
        public string Nome_Pegou { get; set; }
        public string Status { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
