//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public int Id { get; set; }
        public string nomeclien { get; set; }
        public int Expr1 { get; set; }
        public string Raça { get; set; }
        public int Expr2 { get; set; }
        public string Especie { get; set; }
        public int Expr3 { get; set; }
        public string nomefunc { get; set; }
        public int Expr4 { get; set; }
        public string Nome { get; set; }
        public System.DateTime Idade { get; set; }
        public string Observacao { get; set; }
    }
}
